import pandas as pd

def export_to_html(dataset_info, insights, figures):
    """
    Generates a simple HTML report with interactive Plotly charts.
    
    Args:
        dataset_info: dict of dataset info
        insights: list of strings
        figures: list of dicts {'title': str, 'fig': plotly_figure}
    
    Returns:
        str: HTML content
    """
    
    # Generate HTML components for figures
    figures_html = ""
    for item in figures:
        title = item['title']
        fig = item['fig']
        # Convert plotly fig to partial HTML (div)
        fig_html = fig.to_html(full_html=False, include_plotlyjs='cdn')
        
        figures_html += f"""
        <div class="card">
            <h3>{title}</h3>
            {fig_html}
        </div>
        """
    
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>DexAutoEDA Report</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; line-height: 1.6; color: #333; background-color: #f4f6f8; }}
            h1 {{ color: #2c3e50; text-align: center; }}
            h2 {{ color: #34495e; border-bottom: 2px solid #ecf0f1; padding-bottom: 10px; margin-top: 30px; }}
            .card {{ background: #fff; border-radius: 8px; padding: 25px; margin-bottom: 25px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }}
            ul {{ list-style-type: none; padding: 0; }}
            li {{ padding: 8px 0; border-bottom: 1px solid #eee; }}
            .metric {{ font-size: 1.2em; font-weight: bold; color: #2980b9; }}
            .insight {{ background-color: #e8f6f3; padding: 15px; border-left: 5px solid #1abc9c; margin-bottom: 10px; border-radius: 4px; }}
        </style>
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    </head>
    <body>
        <h1>🚀 DexAutoEDA Interactive Report</h1>
        <p style="text-align: center;">Generated by DexAutoEDA</p>
        
        <div class="card">
            <h2>📊 Dataset Info</h2>
            <ul>
                <li>Rows: <span class="metric">{dataset_info.get('rows')}</span></li>
                <li>Columns: <span class="metric">{dataset_info.get('columns')}</span></li>
                <li>Column Names: {", ".join(dataset_info.get('column_list', []))}</li>
            </ul>
        </div>
        
        <div class="card">
            <h2>💡 Key Insights</h2>
            {"".join([f'<div class="insight">{insight}</div>' for insight in insights])}
        </div>
        
        <h2>📈 Visualizations</h2>
        {figures_html}
        
    </body>
    </html>
    """
    return html_content
